### ISSUE TITLE
removing circular dependecies created new error

### ISSUE THREAD

**Issue by Averelll** [nathankunicki/nuimojs#5]
I'm just playing with the nuimo, and your library is great. Got it working in literally minutes. However, in trying interaction.js example, I run into the following:

/etc/nodejs/apps/nuimo/node_modules/nuimojs/src/device.js:180
            case (Nuimo.Direction.LEFT):
                                 ^

TypeError: Cannot read property 'LEFT' of undefined
    at Device._handleSwipe (/etc/nodejs/apps/nuimo/node_modules/nuimojs/src/device.js:180:34)
    at Characteristic.characteristic.on (/etc/nodejs/apps/nuimo/node_modules/nuimojs/src/device.js:156:13)
    at emitTwo (events.js:106:13)
    at Characteristic.emit (events.js:191:7)
    at Noble.onRead (/etc/nodejs/apps/nuimo/node_modules/noble/lib/noble.js:275:20)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)
    at NobleBindings.onNotification (/etc/nodejs/apps/nuimo/node_modules/noble/lib/hci-socket/bindings.js:399:8)
    at emitMany (events.js:127:13)
    at emit (events.js:201:7)

As you remeoved the circular dependency, now the constant is in service.js, and no longer referenced from nuimo.js, so it is now no longer Nuimo.Direction.xxx, but just Direction.xxx. I changed appropriately.

**Comment by nathankellenicki** [comment]
Fixed with #7 (#4 broke an example). Thanks!
